server:
  port: 8080

spring:
  profiles:
    active: local
  flyway:
    enabled: false
  jpa:
    open-in-view: false

kakao:
  auth:
    rest-api-key:
    native-app-key:
    client-secret:
    redirect-uri:

token:
  register-token-expires-in: 300
  access-token-expires-in: 1800
  refresh-token-expires-in: 5184000
  secret:

aws:
  s3:
    bucket: bucket
    access-key-id: accesskeyid
    secret-access-key: secretaccesskey
    presigned-url-expires-in: 86400
