spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:13306/letters_to?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    user: root
    password: root
  datasource:
    url: jdbc:mysql://localhost:13306/letters_to?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE

