version: "3.9"
services:
  spring-app:
    container_name: spring-app
    image: spring-app:custom
    ports:
      - "8080:8080"
    command: java -jar app.jar --spring.profiles.active='${SPRING_PROFILES_ACTIVE}' --spring.datasource.url='${SPRING_DATASOURCE_URL}' --spring.datasource.username='${SPRING_DATASOURCE_USERNAME}' --spring.datasource.password='${SPRING_DATASOURCE_PASSWORD}' --kakao.auth.rest-api-key='${KAKAO_AUTH_REST_API_KEY}' --kakao.auth.native-app-key='${KAKAO_AUTH_NATIVE_APP_KEY}' --kakao.auth.client-secret='${KAKAO_AUTH_CLIENT_SECRET}' --kakao.auth.redirect-uri='${KAKAO_AUTH_REDIRECT_URI}' --apple.auth.rest-api-key='${APPLE_AUTH_REST_API_KEY}' --apple.auth.native-app-key='${APPLE_AUTH_NATIVE_APP_KEY}' --apple.auth.client-secret='${APPLE_AUTH_CLIENT_SECRET}' --apple.auth.redirect-uri='${APPLE_AUTH_REDIRECT_URI}' --token.secret='${TOKEN_SECRET}' --aws.s3.bucket='${AWS_S3_BUCKET}' --aws.s3.access-key-id='${AWS_S3_ACCESS_KEY_ID}' --aws.s3.secret-access-key='${AWS_S3_SECRET_ACCESS_KEY}'
  nginx:
    container_name: nginx
    image: nginx:custom
    ports:
      - "80:80"
    depends_on:
      - spring-app
