version: "3.9"
services:
  spring-app:
    container_name: spring-app
    image: spring-app:custom
    ports:
      - "8080:8080"
    command: java -jar app.jar --spring.profiles.active='${SPRING_PROFILES_ACTIVE}' --spring.datasource.url='${SPRING_DATASOURCE_URL}' --spring.datasource.username='${SPRING_DATASOURCE_USERNAME}' --spring.datasource.password='${SPRING_DATASOURCE_PASSWORD}'
  nginx:
    container_name: nginx
    image: nginx:custom
    ports:
      - "80:80"
    depends_on:
      - spring-app
