version: "3.9"
services:
  letters_to-db:
    container_name: letters_to-db
    image: mysql:8.0.30
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
  letters_to-adminer:
    container_name: letters_to-adminer
    image: adminer:4
    restart: always
    ports:
      - "18080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: letters_to-db
